// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neompzltxilcimodyvpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lb21wemx0eGlsY2ltb2R5dnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTQ3MTEsImV4cCI6MjA2MzE5MDcxMX0.6HgkGyPdVtMlPH0ViERnXRqRNh3ufw_5nsS7fDaWaiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);